pipeline {
    agent {
        docker {
            image 'node:10-alpine'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true' 
    }
    stages {
        stage('install') {
            steps {
                sh 'yarn install'
            }
        }
        stage('Test') { 
            steps {
                sh 'yarn test' 
            }
        }
         stage('build') { 
            steps {
                sh 'yarn build' 
            }
        }
        stage('Deploy') {
            steps {
                input message: 'Do you want to deploy the application? (Click "Proceed" to continue)'
                 sh 'yarn start' 
                 input message: 'Shutdown the app? (Click "Proceed" to continue)'
                 sh 'echo app dead' 
            }
        }
    }
}