pipeline {
    agent {
        docker {
            image 'node:10-alpine'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true' 
    }
    stages {
        stage('install') {
            steps {
                sh 'yarn install'
            }
        }
        stage('Test') { 
            steps {
                sh 'yarn test' 
            }
        }
         stage('build') { 
            steps {
                sh 'yarn build' 
            }
        }


        stage('Deploy') {
            steps {
          withCredentials([
            string(credentialsId: 'heroku_api_key', variable: 'HEROKU_API_KEY')
          ]) {
           sh "export $HEROKU_API_KEY"

            }
        }
    }

        // stage('Deploy') {
        //     steps {
        //     withCredentials([
        //     string(credentialsId: 'heroku_api_key', variable: 'HEROKU_API_KEY'),
        //   ])
        //         // input message: 'Do you want to deploy the application? (Click "Proceed" to continue)'
        //         //  sh 'yarn start' 
        //         sh 'export ${HEROKU_API_KEY}'
        //     }
        // }
    }
}